CREATE TABLE IF NOT EXISTS `User` (
`UserID` INT AUTO_INCREMENT PRIMARY KEY,
`Username` VARCHAR(255) NOT NULL,
`Email` VARCHAR(255) NOT NULL,
`Role` ENUM('Admin', 'User') NOT NULL,
`Password` VARCHAR(255) NOT NULL,
`Photo_Url` VARCHAR(255) DEFAULT NULL,
`Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`Updated_At` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Artist` (
`ArtistID` INT AUTO_INCREMENT PRIMARY KEY,
`Name` VARCHAR(255) NOT NULL,
`Genre` VARCHAR(255) NOT NULL,
`Photo_Url` VARCHAR(255) DEFAULT NULL,
`Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`Updated_At` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Album` (
`AlbumID` INT AUTO_INCREMENT PRIMARY KEY,
`Title` VARCHAR(255) NOT NULL,
`ArtistID` INT,
`Genre` VARCHAR(255) NOT NULL,
`ReleaseDate` DATE NOT NULL,
`Photo_Url` VARCHAR(255) DEFAULT NULL,
`Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`Updated_At` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (`ArtistID`) REFERENCES `Artist`(`ArtistID`)
);

CREATE TABLE IF NOT EXISTS `Track` (
`TrackID` INT AUTO_INCREMENT PRIMARY KEY,
`Title` VARCHAR(255) NOT NULL,
`ArtistID` INT,
`AlbumID` INT,
`TrackLink` VARCHAR(255) NOT NULL,
`Duration` TIME NOT NULL,
`ReleaseDate` DATE NOT NULL,
`Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`Updated_At` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (`ArtistID`) REFERENCES `Artist`(`ArtistID`),
FOREIGN KEY (`AlbumID`) REFERENCES `Album`(`AlbumID`)
);

CREATE TABLE IF NOT EXISTS `Playlist` (
`PlaylistID` INT AUTO_INCREMENT PRIMARY KEY,
`UserID` INT,
`Title` VARCHAR(255) NOT NULL,
`Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`Updated_At` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`)
);

CREATE TABLE IF NOT EXISTS `Likes` (
`LikeID` INT AUTO_INCREMENT PRIMARY KEY,
`UserID` INT,
`TrackID` INT,
`Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`),
FOREIGN KEY (`TrackID`) REFERENCES `Track`(`TrackID`)
);
