server:
  port: 8080

spring:
  application:
    name: "userControl"
  profiles:
    active: "default"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/musicapp
    username: root
    password: root
  batch:
    jdbc:
      schema: classpath:initDatabase/defaultSchemas/Schemas.sql
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  sql:
    init:
      schema-locations: classpath:initDatabase/defaultSchemas/Schemas.sql
  web:
    resources:
      static-locations: file:./src/main/resources/Images/Artists/

api:
  security:
    token:
      secret: "|e?oh&?z$eMG@C^UQ~}8J1,sgJy:,DfE"
    tokenShortDuration:
      expiration: 3600
    tokenLongDuration:
      expiration: 604800
